package com.codehijackers.guldnet.ui.localization

import com.codehijackers.guldnet.repository.AppLanguage

data class GuildnetStrings(
    val home: String,
    val guilds: String,
    val squads: String,
    val search: String,
    val profile: String,

    val clans: String,
    val loreVault: String,
    val settings: String,
    val notifications: String,

    val create: String,
    val cancel: String,
    val save: String,
    val back: String,

    val editProfile: String,
    val displayName: String,
    val username: String,
    val bio: String,

    val language: String,
    val English: String,
    val isiZulu: String,

    val popularDiscussions: String,
    val searchDiscussions: String,
    val noDiscussions: String,

    val openChat: String,
    val createDiscussion: String,
    val publishGuide: String,

    val goodEvening: String,
    val searchSquadsGuidesPlayers: String,
    val recommendedSquads: String,
    val trendingDiscussions: String,
    val yourCommunities: String,
    val noSquadsMatchSearch: String,
    val noCommunitiesJoined: String,
    val matches: String,
    val winRate: String,
    val rank: String,
    val plusThreeToday: String,
    val topFifteenPercent: String,
    val upFromSilver: String,
    val seeAll: String,
    val members: String,
    val online: String,
    val joined: String,
    val join: String,

    val findAndJoinGamingCommunities: String,
    val createGuild: String,

    val searchSquads: String,
    val mySquads: String,
    val popular: String,
    val noSquadsFound: String,
    val noSquadsJoined: String,
    val noSquadsAvailable: String,
    val explorePopularSquads: String,
    val chat: String,
    val view: String,

    val squadNotFound: String,
    val communityActive: String,
    val status: String,
    val open: String,
    val squadChat: String,
    val chatWithSquadMembers: String,
    val joinSquadToEnterChat: String,
    val joinSquadToChat: String,
    val community: String,
    val gamingCommunity: String,
    val backToSquads: String,

    val createSquadDescription: String,
    val squadName: String,
    val squadNamePlaceholder: String,
    val description: String,
    val squadDescriptionPlaceholder: String,
    val createSquad: String,
    val cancelSquad: String,

    val searchGuildnet: String,

    val communities: String,
    val findGamingCommunities: String,

    val discussionTitle: String,
    val discussionTitlePlaceholder: String,
    val category: String,
    val strategy: String,
    val discussionContent: String,
    val discussionContentPlaceholder: String,

    val clansForum: String,
    val noDiscussionsFound: String,
    val tryDifferentSearch: String,
    val startDiscussionWithGuild: String,
    val categoryStrategy: String,
    val categoryBuilds: String,
    val categoryPatchNotes: String,
    val categoryHighlights: String,
    val hot: String,
    val discussionsCount: String,

    val discussion: String,
    val discussionNotFound: String,
    val responses: String,
    val addResponse: String,
    val joinDiscussion: String,
    val postResponse: String,

    val squadChatPlaceholder: String,
    val squadLabel: String,
    val send: String,
    val you: String,

    val lore: String,
    val vault: String,
    val createGuide: String,
    val searchGuidesLore: String,
    val all: String,
    val noGuidesFound: String,
    val tryAnotherSearchCategory: String,
    val featuredGuides: String,
    val allGuides: String,
    val featured: String,
    val byAuthor: String,
    val minRead: String,
    val views: String,

    val guideNotFound: String,
    val bookmark: String,
    val loreVaultLabel: String,
    val by: String,

    val shareGamingKnowledge: String,
    val guideTitle: String,
    val guideTitlePlaceholder: String,
    val guideCategoryPlaceholder: String,
    val guideDescriptionPlaceholder: String,
    val guideContent: String,
    val guideContentPlaceholder: String,

    val postNotFound: String,
    val comments: String,
    val addComment: String,
    val comment: String,
    val postComment: String,

    val guildPosts: String,
    val communityDiscussions: String,
    val createPost: String,

    val postTitle: String,
    val postTitlePlaceholder: String,
    val content: String,
    val postContentPlaceholder: String,

    val account: String,
    val preferences: String,
    val on: String,
    val off: String,
    val privacy: String,
    val theme: String,
    val squadRank: String,
    val posts: String,

    val changeAvatar: String,
    val saveChanges: String,

    val languageSettingsDescription: String,

    val darkPurple: String,
    val royalPacific: String,
    val sabeins: String,
    val velvetBloom: String,
    val darkPurpleDescription: String,
    val royalPacificDescription: String,
    val sabeinsDescription: String,
    val velvetBloomDescription: String,

    val themeSettingsDescription: String,
)

fun guildnetStrings(
    language: AppLanguage
): GuildnetStrings {

    return when (language) {

        AppLanguage.ENGLISH -> GuildnetStrings(

            home = "Home",
            guilds = "Guilds",
            squads = "Squads",
            search = "Search",
            profile = "Profile",

            clans = "Clans",
            loreVault = "LoreVault",
            settings = "Settings",
            notifications = "Notifications",

            create = "Create",
            cancel = "Cancel",
            save = "Save",
            back = "Back",

            editProfile = "Edit Profile",
            displayName = "Display Name",
            username = "Username",
            bio = "Bio",

            language = "Language",
            English = "English",
            isiZulu = "isiZulu",

            popularDiscussions = "Popular Discussions",
            searchDiscussions = "Search discussions...",
            noDiscussions = "No discussions yet",

            openChat = "Open Chat",
            createDiscussion = "Create Discussion",
            publishGuide = "Publish Guide",

            goodEvening = "Good evening,",
            searchSquadsGuidesPlayers = "Search squads, guides, players...",
            recommendedSquads = "Recommended Squads",
            trendingDiscussions = "Trending Discussions",
            yourCommunities = "Your Communities",
            noSquadsMatchSearch = "No squads match your search.",
            noCommunitiesJoined = "You have not joined any communities yet.",
            matches = "Matches",
            winRate = "Win Rate",
            rank = "Rank",
            plusThreeToday = "+3 today",
            topFifteenPercent = "Top 15%",
            upFromSilver = "↑ from Silver",
            seeAll = "See All",
            members = "members",
            online = "online",
            joined = "Joined",
            join = "Join",
            createGuild = "Create Guild",
            findAndJoinGamingCommunities = "Find and join gaming communities.",

            searchSquads = "Search squads...",
            mySquads = "My Squads",
            popular = "Popular",
            noSquadsFound = "No squads found",
            noSquadsJoined = "You haven't joined any squads yet.",
            noSquadsAvailable = "No squads available.",
            explorePopularSquads = "Explore Popular squads to find a community.",
            chat = "Chat",
            view = "View",

            squadNotFound = "Squad not found",
            communityActive = "Community active",
            status = "Status",
            open = "Open",
            squadChat = "Squad Chat",
            chatWithSquadMembers = "Chat with your squad members",
            joinSquadToEnterChat = "Join the squad to enter chat",
            joinSquadToChat = "Join Squad to Chat",
            community = "Community",
            gamingCommunity = "Gaming community",
            backToSquads = "Back to Squads",

            createSquadDescription = "Create a group for real-time gaming chat.",
            squadName = "Squad Name",
            squadNamePlaceholder = "Example: Minecraft Survival Crew",
            description = "Description",
            squadDescriptionPlaceholder = "What is this Squad about?",
            createSquad = "Create Squad",
            cancelSquad = "Cancel",

            searchGuildnet = "Search Guildnet.",

            communities = "Communities",
            findGamingCommunities = "Find your gaming communities.",

            discussionTitle = "TITLE *",
            discussionTitlePlaceholder = "Give your discussion a title...",
            category = "CATEGORY *",
            strategy = "Strategy",
            discussionContent = "CONTENT *",
            discussionContentPlaceholder = "Share your thoughts with the clan...",

            clansForum = "Clans Forum",
            noDiscussionsFound = "No discussions found",
            tryDifferentSearch = "Try a different search.",
            startDiscussionWithGuild = "Start a discussion with your guild.",
            categoryStrategy = "Strategy",
            categoryBuilds = "Builds",
            categoryPatchNotes = "Patch Notes",
            categoryHighlights = "Highlights",
            hot = "Hot",
            discussionsCount = "discussions",

            discussion = "Discussion",
            discussionNotFound = "Discussion not found",
            responses = "RESPONSES",
            addResponse = "ADD A RESPONSE",
            joinDiscussion = "Join the discussion...",
            postResponse = "Post Response",

            squadChatPlaceholder = "Type a message...",
            squadLabel = "Squad",
            send = "Send",
            you = "You",

            lore = "Lore",
            vault = "Vault",
            createGuide = "Create Guide",
            searchGuidesLore = "Search guides & lore...",
            all = "All",
            noGuidesFound = "No guides found",
            tryAnotherSearchCategory = "Try another search or category.",
            featuredGuides = "Featured Guides",
            allGuides = "All Guides",
            featured = "Featured",
            byAuthor = "by",
            minRead = "min read",
            views = "views",

            guideNotFound = "Guide not found",
            bookmark = "Bookmark",
            loreVaultLabel = "LoreVault",
            by = "by",

            shareGamingKnowledge = "Share your gaming knowledge",
            guideTitle = "Guide Title",
            guideTitlePlaceholder = "Example: Ultimate Beginner Guide",
            guideCategoryPlaceholder = "Builds, Tactics, Tutorial...",
            guideDescriptionPlaceholder = "Briefly describe your guide",
            guideContent = "Guide Content",
            guideContentPlaceholder = "Write your guide here...",
            postNotFound = "Post not found",
            comments = "Comments",
            addComment = "Add a Comment",
            comment = "Comment",
            postComment = "Post Comment",

            guildPosts = "Guild Posts",
            communityDiscussions = "Community discussions",
            createPost = "Create Post",

            postTitle = "Post Title",
            postTitlePlaceholder = "What do you want to discuss?",
            content = "Content",
            postContentPlaceholder = "Write your post...",

            account = "ACCOUNT",
            preferences = "PREFERENCES",
            on = "On",
            off = "Off",
            privacy = "Privacy",
            theme = "Theme",
            squadRank = "Squad Rank",
            posts = "Posts",

            changeAvatar = "Change Avatar",
            saveChanges = "Save Changes",

            languageSettingsDescription = "Choose the language used across GuildNet.",

            darkPurple = "Dark Purple",
            royalPacific = "Royal Pacific",
            sabeins = "Sabeins",
            velvetBloom = "Velvet Bloom",

            darkPurpleDescription = "Guildnet's classic dark purple theme",
            royalPacificDescription = "Royal blue, cyan and white",
            sabeinsDescription = "Black, red and gold",
            velvetBloomDescription = "Royal pink and velvet purple",
            themeSettingsDescription = "Choose the visual style used across Guildnet.",
        )

        AppLanguage.ZULU -> GuildnetStrings(

            home = "Ikhaya",
            guilds = "AmaGuild",
            squads = "Amaqembu",
            search = "Sesha",
            profile = "Iphrofayela",

            clans = "Izingxoxo",
            loreVault = "LoreVault",
            settings = "Izilungiselelo",
            notifications = "Izaziso",

            create = "Dala",
            cancel = "Khansela",
            save = "Gcina",
            back = "Emuva",

            editProfile = "Hlela Iphrofayela",
            displayName = "Igama Lokuboniswa",
            username = "Igama Lomsebenzisi",
            bio = "Mayelana nami",

            language = "Ulimi",
            English = "English",
            isiZulu = "isiZulu",

            popularDiscussions = "Izingxoxo Ezidumile",
            searchDiscussions = "Sesha izingxoxo...",
            noDiscussions = "Azikho izingxoxo okwamanje",

            openChat = "Vula Ingxoxo",
            createDiscussion = "Dala Ingxoxo",
            publishGuide = "Shicilela Umhlahlandlela",

            goodEvening = "Sawubona kusihlwa,",
            searchSquadsGuidesPlayers = "Sesha ama-Squad, imihlahlandlela, abadlali...",
            recommendedSquads = "Ama-Squad Anconyiwe",
            trendingDiscussions = "Izingxoxo Ezidumile",
            yourCommunities = "Imiphakathi Yakho",
            noSquadsMatchSearch = "Ayikho i-Squad ehambisana nosesho lwakho.",
            noCommunitiesJoined = "Awukajini noma yimuphi umphakathi.",
            matches = "Imidlalo",
            winRate = "Izinga Lokuwina",
            rank = "Isikhundla",
            plusThreeToday = "+3 namuhla",
            topFifteenPercent = "Phezulu ngo-15%",
            upFromSilver = "↑ usuka e-Silver",
            seeAll = "Bona Konke",
            members = "amalungu",
            online = "ku-inthanethi",
            joined = "Ujoyinile",
            join = "Joyina",
            createGuild = "Dala i-Guild",
            findAndJoinGamingCommunities = "Thola futhi ujoyine imiphakathi yemidlalo.",

            searchSquads = "Sesha ama-Squad...",
            mySquads = "Ama-Squad Ami",
            popular = "Adumile",
            noSquadsFound = "Awekho ama-Squad atholakele",
            noSquadsJoined = "Awukajoyini noma yimaphi ama-Squad okwamanje.",
            noSquadsAvailable = "Awekho ama-Squad atholakalayo.",
            explorePopularSquads = "Hlola ama-Squad adumile ukuze uthole umphakathi.",
            chat = "Ingxoxo",
            view = "Buka",

            squadNotFound = "I-Squad ayitholakali",
            communityActive = "Umphakathi uyasebenza",
            status = "Isimo",
            open = "Vuliwe",
            squadChat = "Ingxoxo ye-Squad",
            chatWithSquadMembers = "Xoxa namalungu e-Squad yakho",
            joinSquadToEnterChat = "Joyina i-Squad ukuze ungene engxoxweni",
            joinSquadToChat = "Joyina i-Squad ukuze Uxoxe",
            community = "Umphakathi",
            gamingCommunity = "Umphakathi wabadlali",
            backToSquads = "Buyela Kuma-Squad",

            createSquadDescription = "Dala iqembu lengxoxo yemidlalo yesikhathi sangempela.",
            squadName = "Igama le-Squad",
            squadNamePlaceholder = "Isibonelo: Iqembu le-Minecraft Survival",
            description = "Incazelo",
            squadDescriptionPlaceholder = "Le-Squad imayelana nani?",
            createSquad = "Dala i-Squad",
            cancelSquad = "Khansela",

            searchGuildnet = "Sesha ku-Guildnet.",

            communities = "Imiphakathi",
            findGamingCommunities = "Thola imiphakathi yakho yemidlalo.",

            discussionTitle = "ISIHLOKO *",
            discussionTitlePlaceholder = "Nikeza ingxoxo yakho isihloko...",
            category = "ISIGABA *",
            strategy = "Amasu",
            discussionContent = "OKUQUKETHWE *",
            discussionContentPlaceholder = "Yabelana ngemicabango yakho ne-clan...",

            clansForum = "Iforamu Yama-Clan",
            noDiscussionsFound = "Azikho izingxoxo ezitholakele",
            tryDifferentSearch = "Zama olunye usesho.",
            startDiscussionWithGuild = "Qala ingxoxo ne-Guild yakho.",
            categoryStrategy = "Amasu",
            categoryBuilds = "Ukwakha",
            categoryPatchNotes = "Amanothi Ezibuyekezo",
            categoryHighlights = "Okuvelele",
            hot = "Kuyashisa",
            discussionsCount = "izingxoxo",
            discussion = "Ingxoxo",
            discussionNotFound = "Ingxoxo ayitholakali",
            responses = "IZIMPENDULO",
            addResponse = "ENZA IMPENDULO",
            joinDiscussion = "Joyina ingxoxo...",
            postResponse = "Thumela Impendulo",

            squadChatPlaceholder = "Bhala umlayezo...",
            squadLabel = "I-Squad",
            send = "Thumela",
            you = "Wena",

            lore = "Umlando",
            vault = "Vault",
            createGuide = "Dala Umhlahlandlela",
            searchGuidesLore = "Sesha imihlahlandlela nomlando...",
            all = "Konke",
            noGuidesFound = "Ayikho imihlahlandlela etholakele",
            tryAnotherSearchCategory = "Zama olunye usesho noma isigaba.",
            featuredGuides = "Imihlahlandlela Evelele",
            allGuides = "Yonke Imihlahlandlela",
            featured = "Evelele",
            byAuthor = "ngu-",
            minRead = "imiz. yokufunda",
            views = "ukubukwa",

            guideNotFound = "Umhlahlandlela awutholakali",
            bookmark = "Beka uphawu lokubekisa",
            loreVaultLabel = "LoreVault",
            by = "ngu-",

            shareGamingKnowledge = "Yabelana ngolwazi lwakho lwemidlalo",
            guideTitle = "Isihloko Somhlahlandlela",
            guideTitlePlaceholder = "Isibonelo: Umhlahlandlela Ophelele Wabaqalayo",
            guideCategoryPlaceholder = "Ukwakha, Amasu, Okokufundisa...",
            guideDescriptionPlaceholder = "Chaza kafushane umhlahlandlela wakho",
            guideContent = "Okuqukethwe Komhlahlandlela",
            guideContentPlaceholder = "Bhala umhlahlandlela wakho lapha...",

            postNotFound = "Okuthunyelwe akutholakali",
            comments = "Amazwana",
            addComment = "Engeza Amazwana",
            comment = "Amazwana",
            postComment = "Thumela Amazwana",

            guildPosts = "Okuthunyelwe Kwe-Guild",
            communityDiscussions = "Izingxoxo zomphakathi",
            createPost = "Dala Okuthunyelwe",

            postTitle = "Isihloko Sokuthunyelwe",
            postTitlePlaceholder = "Yini ofuna ukuxoxa ngayo?",
            content = "Okuqukethwe",
            postContentPlaceholder = "Bhala okuthunyelwe kwakho...",

            account = "I-AKHAWUNTI",
            preferences = "IZINKETHO",
            on = "Kuvuliwe",
            off = "Kuvaliwe",
            privacy = "Ubumfihlo",
            theme = "Itimu",
            squadRank = "Izinga le-Squad",
            posts = "Okuthunyelwe",

            changeAvatar = "Shintsha I-Avatar",
            saveChanges = "Londoloza Izinguquko",

            languageSettingsDescription = "Khetha ulimi olusetshenziswa kuyo yonke i-GuildNet.",
            darkPurple = "Okunsomi Okumnyama",
            royalPacific = "Royal Pacific",
            sabeins = "Sabeins",
            velvetBloom = "Velvet Bloom",

            darkPurpleDescription = "Itimu yakudala ye-Guildnet enombala onsomi omnyama",
            royalPacificDescription = "Okuluhlaza okwesibhakabhaka, i-cyan nokumhlophe",
            sabeinsDescription = "Okumnyama, okubomvu negolide",
            velvetBloomDescription = "Okuphinki kweRoyal nokunsomi kwevelvet",

            themeSettingsDescription = "Khetha isitayela esibonakalayo esisetshenziswa kuyo yonke i-Guildnet.",
        )
    }
}